name: Gerar APK Dr. Agrícola

on:
  workflow_dispatch:

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Preparar projeto Android
        run: |
          rm -rf projeto
          mkdir projeto
          unzip -q Dr_Agricola_V6_Android.zip -d projeto

          cd projeto

          mv App app
          mv Build.gradle build.gradle
          mv Settings settings.gradle

          mv app/src/main/Java app/src/main/java
          mv app/src/main/Res app/src/main/res
          mv app/src/main/Assets app/src/main/assets

          mv app/src/main/java/com/dragricola/App app/src/main/java/com/dragricola/app

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        working-directory: projeto
        run: gradle assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: Dr-Agricola-APK
          path: projeto/app/build/outputs/apk/debug/*.apk
